version: '3'
services:
  laravel-app:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: laravel-app
      
    environment:
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_KEY=
      - APP_DEBUG=true
      - APP_URL=http://laravel-app:8000
      - DB_CONNECTION=mysql_db
      - DB_HOST=mysql_db
      - DB_PORT=3306
      - DB_DATABASE=innyx_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - mysql_db
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - laravel-app
    networks:
      - mynetwork

  mysql_db:
    image: mysql:latest
    container_name: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "4306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=innyx_db
    networks:
      - mynetwork

  vue-app:
    build:
      context: .
      dockerfile: Dockerfile_frontend
    container_name: vue-app
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    depends_on:
      - laravel-app

networks:
  mynetwork:

volumes:
  mysql_data:
